### ISSUE TITLE
Translating the README.md into Spanish

### ISSUE THREAD

**Issue by ghost** [misprit7/computerraria#24]
## Request:
I noticed that currently the README.md file is only available it English, and I believe that having it translated into multiple languages could greatly benefit non-English-speaking users. This would make the project more accessible to a broader audience.

## Volunteer Offer:
I would like to offer my help in translating the README.md file into Spanish, as I am fluent both English and Spanish.

If you are open to the idea, I would like to ask for any translation guidelines that you may have. I am open to collaboration and willing to follow any preferred procedures.

Thank you for considering this request. I am excited about the opportunity to contribute to the project in this way. Looking forward to your feedback.

Best regards, Iker.

**Comment by misprit7** [comment]
I'd like to avoid having multiple versions of the readme that I have to keep up to date, so I think I'll keep it English-only right now. Thanks for the offer though!
